<img style="float: left;;" src='../Figures/iteso.jpg' width="50" height="100"/></a>

# <center> <font color= #000047> Repaso de la Librería NumPy</font> </center>



# NumPy 

NumPy es una poderosa librería de álgebra lineal para Python. Lo que lo hace tan importante es que casi todas las librerías en el ecosistema de <a href='https://pydata.org/'>PyData</a> (pandas, scipy, scikit-learn, etc.) utilizan NumPy como uno de sus principales componentes básicos. 

NumPy también es increíblemente rápido, ya que tiene enlaces a bibliotecas C.

Aquí repasaremos los conceptos básicos de NumPy.

## Usando NumPy


In [1]:
import numpy as np


NumPy tiene muchas funciones y capacidades integradas. No veremos todos, nos centraremos en algunos de los aspectos más importantes de NumPy qué nos serán de utilidad en el curso como son: vectores, arreglos, matrices y generación de números aleatorios. 

# Arreglos en NumPy 

Los arreglos de NumPy son la principal forma en que utilizaremos esta librería a lo largo del curso. Los arreglos en NumPy se construyen de dos formas: vectores y matrices. Los vectores son matrices estrictamente unidimensionales (1D) y las matrices son elementos en 2D (pero se debe tener en cuenta que una matriz puede tener solo una fila o una columna) no son estrictamente cuadradas.

## Creando Arreglos en NumPy

### De una Lista de Python 

Podemos crear un arreglo directamente de una lista o listas de listas:



In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [7]:
my_array = np.array(my_list)
my_array.shape

(3,)

In [14]:
my_list_mat = [(1,2,3),(4,3,4),(8,7,9)]
my_list_mat2 = [[1,2,3],[4,3,4],[8,7,9]]

In [11]:
my_list_mat

[(1, 2, 3), (4, 3, 4), (8, 7, 9)]

In [15]:
my_list_mat2

[[1, 2, 3], [4, 3, 4], [8, 7, 9]]

In [12]:
my_mat = np.array(my_list_mat)

In [16]:
my_mat2 = np.array(my_list_mat2)

In [18]:
my_mat3 = np.array([[1,2],[2,3]])

In [13]:
my_mat

array([[1, 2, 3],
       [4, 3, 4],
       [8, 7, 9]])

In [17]:
my_mat2

array([[1, 2, 3],
       [4, 3, 4],
       [8, 7, 9]])

In [19]:
my_mat3

array([[1, 2],
       [2, 3]])

In [20]:
np.matrix([[1,2],[2,3]])

matrix([[1, 2],
        [2, 3]])

In [22]:
np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

## Métodos incorporados en NumPy

Hay muchas formas de como generar arreglos usando métodos incorporados.

### arange

Devuelve valores espaciados uniformemente dentro de un intervalo dado. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [25]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### Creando arreglos de Ceros (zeros) y Unos (ones)

Podemos generar matrices de ceros ó unos. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
x = np.ones((5,5))

In [33]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
x.astype(int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### linspace 
Este método devuelve números espaciados uniformemente durante un intervalo especificado.[[referencia](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [35]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [36]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [37]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

<font color=green>Note que `.linspace()` *incluye* el valor de paro. Para obtener un arreglo con fracciones comunes, hay que aumentar el numero de elementos:</font>

### eye

Mediante este método podemos crear la matriz identidad.[[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [38]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 
Numpy también tiene muchas formas de crear arreglos de números aleatorios:

### rand

Mediante este método podemos crear un arreglo de un tamaño dado con muestras aleatorias de una distribución uniforme en el intervalo ``[0, 1)``.[[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [39]:
np.random.rand(2)

array([0.53722443, 0.39803119])

In [40]:
np.random.rand(2,3)

array([[0.45563905, 0.71469469, 0.09593848],
       [0.95648025, 0.68096971, 0.96475501]])

### randn

Este método devuelve una muestra (o muestras) de la distribución "normal estándar" [σ = 1] A diferencia de **rand**, que es uniforme, es más probable que aparezcan valores más cercanos a cero. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]


In [41]:
np.random.randn(2)

array([-0.02949053,  0.25776419])

### randint
Devuelve números enteros aleatorios de un intervalo `mínimo` (inclusive) a `máximo` (exclusivo).  [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [42]:
np.random.randint(1,100,10)

array([84, 22,  3, 73, 59, 71, 74, 66, 27, 27])

### seed
Se puede utilizar para establecer el estado aleatorio, de modo que se puedan reproducir los mismos resultados "aleatorios". [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [43]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [45]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Atributos y métodos de un Arreglo

Analicemos algunos atributos y métodos útiles para un arreglo:

In [48]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
rarr = np.random.randint(0,51,10)
rarr

array([21, 43, 24, 48, 26, 41, 27, 15, 14, 46])

In [52]:
rarr.shape

(10,)

## Reshape
Devuelve una matriz que contiene los mismos datos con una nueva forma. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [54]:
arr.shape

(25,)

In [64]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

Estos son métodos útiles para encontrar valores máximos o mínimos. O para encontrar el índice donde tenemos valores máximos o mínimos:

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
arr.max()

24

In [58]:
arr.min()

0

In [59]:
rarr

array([21, 43, 24, 48, 26, 41, 27, 15, 14, 46])

In [60]:
rarr.max()

48

In [61]:
rarr.argmax()

3

In [62]:
rarr.argmin()

8

## Shape

Shape es un atributo que tienen los arreglos (no un método): [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [66]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
arr.shape

(5, 5)

### dtype

Podemos también obtener el tipo de datos del objeto en el arreglo. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [67]:
arr.dtype

dtype('int64')

In [ ]:
0000 0000
1000 0000 -> 2^8

1111 1111 -> 

11111111 -> 