<img style="float: left;;" src='../Figures/iteso.jpg' width="50" height="100"/></a>

# <center> <font color= #000047> Repaso de la Librería NumPy</font> </center>


# NumPy Indexación y selección

En este apartado veremos como seleccionar elementos o grupos de elementos de un arreglo.

In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Selección e indexación mediante Brackets
La forma más sencilla de elegir uno o algunos elementos de un arreglo es muy similar a las listas de Python:

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[6:9]

array([6, 7, 8])

## Broadcasting

Los arreglos en NumPy se diferencian de las listas normales de Python debido a su capacidad para reasignar valores. Con las listas, solo puede reasignar partes de una lista con partes nuevas del mismo tamaño y forma. Es decir, si quisiera reemplazar los primeros 5 elementos de una lista con un nuevo valor, tendría que pasar una nueva lista de 5 elementos. Con los arreglos de NumPy, podemos reasignar un solo valor a través de un conjunto más grande de valores:


In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_arr[:] = 99
slice_arr

array([99, 99, 99, 99, 99, 99])

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Los datos no se copian, sólo es un pedazo del arreglo original.

In [15]:
arr_copy = arr.copy()

In [17]:
arr_copy[0:5]=10
arr_copy

array([10, 10, 10, 10, 10, 99,  6,  7,  8,  9, 10])

## Indexación de un arreglo 2D (matrices)

Lo forma general es: **arr_2d[row][col]** o **arr_2d[row,col]**.

In [18]:
arr_2d = np.array([[5,10,15],
                   [20,25,30],
                   [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
arr_2d[1][1]

25

In [21]:
arr_2d[1,1]

25

In [23]:
arr_2d[0]

array([ 5, 10, 15])

In [25]:
arr_2d[0,0:2]

array([ 5, 10])

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [34]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [36]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

## Más sobre indexación
Indexar una matriz 2D puede ser un poco confuso al principio, especialmente cuando se tiene un mator tamaño en la matriz.

Una imagen útil para entender el concepto de indexación:

<img src= 'numpy_indexing.png' width=500/> 

## Selección Condicional

Este es un concepto muy fundamental que nos servirá en la librería de Pandas más adelante, ¡asegúrate de entender esta parte!


In [38]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [41]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [42]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
x=2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
a = 3*np.ones(10)
a

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [46]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[arr==3]

array([3])

In [49]:
a = 3


In [50]:
a == 3

True