<div style="text-align: right"> 02/02 </div>
<h1><center>Repaso de la Librería NumPy</center></h1>

# Operaciones con NumPy

## Aritméticas

Podemos realizar fácilmente aritmeticas como *arreglo con arreglo* , o *escalar con arreglo*. Veamos algunos ejemplos: 

In [1]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
arr=arr.reshape(1,10)

In [8]:
arr.shape

(1, 10)

(1x10)x(1x10)

(1x10)x(10x1) = (1x1)

In [9]:
arr2 = arr.transpose()

In [10]:
arr2.shape

(10, 1)

In [11]:
arr.shape

(1, 10)

In [12]:
np.dot(arr,arr2)

array([[285]])

In [15]:
np.matmul(arr,arr2)

array([[285]])

In [21]:
# Crear una matriz aleatoria de números enteros de dimensión 4x2 -> A
# Crear una matriz aleatoria de números enteros de dimensión 2x6 -> B
# Realizar la multiplicación de Matrices C = A*B
# Realizar la multiplicación de Matrices C = B*A

A = np.random.randint(100,size=(4,2))
B = np.random.randint(100,size=(2,6))




In [22]:
C = A*B

ValueError: operands could not be broadcast together with shapes (4,2) (2,6) 

In [23]:
C = np.dot(A,B)
C

array([[ 6336,  2358, 10944,  1836,  8010,  9468],
       [ 2624,  1378,  5260,  1028,  3334,  4908],
       [ 8160,  2151, 12489,  1774, 10279, 10016],
       [ 4352,   520,  5524,   528,  5456,  3800]])

In [24]:
C = np.dot(B,A)

ValueError: shapes (2,6) and (4,2) not aligned: 6 (dim 1) != 4 (dim 0)

## Funciones universales en los Arreglos

NumPy viene con muchass [funciones universales en los arreglos](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, que son esencialmente operaciones matemáticas que se pueden aplicar al arreglo.<br>Veamos algunas funciones más comunes:

In [31]:
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [27]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [28]:
np.exp(arr)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03]])

In [29]:
np.sin(arr)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [35]:
arr.min()

0

In [36]:
arr.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [37]:
arr.transpose()

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [30]:
np.log(arr)

<ipython-input-30-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
        1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458]])

## Resumen de Estadística sobre Arreglos

NumPy también ofrece métodos estadísticos como <em> sum </em>, <em> mean </em> y <em> max </em>. 

In [32]:
arr.sum()

45

In [33]:
np.sum(arr)

45

In [38]:
arr.var()

8.25

In [39]:
arr.std()

2.8722813232690143

In [40]:
arr.max()

9

## Lógica para el eje (axis)

Cuando trabajamos con arreglos bidimensionales, debemos considerar filas y columnas. En términos de un arreglo, el eje 0 (cero) es el eje horizontal (filas) y el eje 1 es el eje vertical (columnas). Los valores (0,1) corresponden al orden en el que método <tt> arr.shape </tt> da como salida.

Veamos cómo afecta esto a nuestros cálculos estadísticos resumidos de arriba.


In [43]:
A

array([[90, 54],
       [54, 14],
       [79, 88],
       [16, 60]])

In [42]:
A.sum(axis=0)

array([239, 216])

In [44]:
A.sum(axis=1)

array([144,  68, 167,  76])

Dando como entrada <tt>axis=0</tt>, estamos devolviendo la suma del arreglo a lo largo del eje vertical, esencialmente <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

<img src='axis_logic.png' width=400/>

In [45]:
A.sum()

455

Esto nos dice que <tt>arr_2d</tt> tiene 3 filas y 4 columnas.

En <tt>arr_2d.sum(axis=0)</tt>, se sumó el primer elemento de cada fila, luego el segundo elemento y así sucesivamente.

Entonces, ¿qué debería <tt>arr_2d.sum(axis=1)</tt> regresar?